all: server.c
#	@echo "Please modify Makefile!"
	$ gcc server.c -D WRITE_SERVER -o write_server
	$ gcc server.c -D READ_SERVER -o read_server

clean:
#	@echo "Please modify Makefile!"
	rm -f write_server
	rm -f read_server


